### ISSUE TITLE
Incorrect name offset in `KeyParameters` for `V1`

### ISSUE THREAD

**Issue by liorwurl** [bdsoha/vitrea-client#18]

**Comment by bdsoha** [comment]
Please provide a sample `buffer` and the `expected` results and a test can be added to guarantee the issue/feature is added/resolved.

**Comment by bdsoha** [comment]
@liormorad It seems like the correct offset should be `20` for `V1.

**Comment by liorwurl** [comment]
That fix works for me as well.

**Comment by bdsoha** [comment]
@liorwurl I just merged the changes into the `develop` branch.
