### ISSUE TITLE
"Scenario" devices are not supported

### ISSUE THREAD

**Issue by liormorad** [bdsoha/vitrea-client#22]
Vitera has its own scenario infrastructure, the type is considered as 0X0 which collides with the lib 'UNDEFINED' value.

Though a better design would be to create scenario logisc in a higher level (i.e. Apple HomeKit),
it should be decided whether it needs to be supported as well. (i.e. Trigger a scenario start)

**Comment by bdsoha** [comment]
@liormorad I personally defined all the *multiway* functionality straight into *Vitrea*. On the other hand, all scenarios were defined in *HomeKit*.

**Comment by bdsoha** [comment]
@liormorad Any updates?

**Comment by liormorad** [comment]
After further examination, the "scenario" feature is very limited,
e.g. you cannot turn off a light after it was on 2 hours.
Thefore - it would be better to focus on other issues and use Homekit/Homebridge for rich logics scenarios
