### ISSUE TITLE
Question: How to Integrate Vitrea Vtouch pro with home assistant?

### ISSUE THREAD

**Issue by smartnakh** [bdsoha/vitrea-client#32]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.

### Example Code

```node
is it possible to get the status of the switches and send command to the switches ?
```

### Description

Hi,

My friend has a vitrea home and wants to get support for the google assistant

i am looking for a way to interact with the Vtouch pro

i am not sure to have understood if this repository can help me or how to use it
 

### Package Version

2

### Protocol Version

V2 (Default)

### NodeJS Version

2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by bdsoha** [comment]
Absolutely, that is something that I am personally doing in my own home.
_Home Assistant_ has the ability to directly connect to HomeKit enabled accessories.

**Comment by smartnakh** [comment]
Excellent News Benyomin !

i am not sure to have understood your answer.

i have homeassistant already running in a docker container, should I just try to add a homekit integration and the Vitrea devices will be detected?

if yes, i don't understand the goal of this repository

אשמח בימים טובים יותר לדבר על זה

תודה

**Comment by bdsoha** [comment]
This repository, as its name states, is a **client** that can be used in other building blocks as you see fit.
It provides the requests and response objects needed to trigger and respond to changes in Vitrea.

Think of it as you would an *http-client**.

**Comment by smartnakh** [comment]
Thanks for your answer

sorry for my direct answer if it was inappropriate

If i have well understood, the script should run as a service and the vitrea devices could be integrated as a home kit device

Concerning the parameters, i assume that the host is the internal IP of the vitrea box. Right ?

are the username and password the one used in the vitrea application?

thanks in advance

Really appreciate !

**Comment by bdsoha** [comment]
No worries.
The IP, username, and password are identical to the ones you use to connect using the visual application.

---

I've been wanting to publish a separate repository for the HomeKit integration for a while but haven't had the time. If you're interested in contributing, please send me an email, and we can discuss this further offline.

**Comment by smartnakh** [comment]
Thanks !

I will be glad to contribute!

I will Contact you. have an excellent day!

**Comment by smartnakh** [comment]
`smh@mbox:/ $ cd home/smh/volumes/v2/
smh@mbox:~/volumes/v2 $ npm list
gn@1.0.0 /home/smh/volumes/v2
└── vitrea-client@0.0.1-alpha.0 (git+ssh://git@github.com/bdsoha/vitrea-client.git#63ec5195c40fe15e363a3daa6de4b21468a18c45)

smh@mbox:~/volumes/v2 $ sudo npm install bdsoha/vitrea-client

up to date, audited 4 packages in 13s

found 0 vulnerabilities
`
